INSERT INTO DOCUMENTS(PROJECT_ID, SPECIALTY_ID, TYPE_ID, DOCNUMBER, TITLE)
  SELECT P.PROJECT_ID, S.SPECIALTY_ID, L.LOOKUP_ID, DR.DOCNUMBER, DR.TITLE
  FROM DOCUMENTS_RAW DR
  INNER JOIN V_PROJECTS P ON P.CODE = DR.PROJECT_CODE AND (DR.SUBPROJECT_CODE IS NULL OR DR.SUBPROJECT_CODE = '' OR DR.SUBPROJECT_CODE = P.SUBPROJECT_CODE)
  INNER JOIN SPECIALTIES S ON DR.SPECIALTY_ABBR = S.ABBREVIATION
  INNER JOIN LOOKUPS L ON L.TYPE = 'tipoDoc' AND DR.TYPE = L.CODE
  WHERE DR.DOCNUMBER NOT IN (SELECT D.DOCNUMBER FROM DOCUMENTS D);

UPDATE
    DOCUMENTS D
SET
    (D.SPECIALTY_ID, D.TYPE_ID, D.TITLE) = 
(SELECT S.SPECIALTY_ID, L.LOOKUP_ID, DR.TITLE
  FROM DOCUMENTS_RAW DR
  INNER JOIN V_PROJECTS P ON P.CODE = DR.PROJECT_CODE AND (DR.SUBPROJECT_CODE IS NULL OR DR.SUBPROJECT_CODE = '' OR DR.SUBPROJECT_CODE = P.SUBPROJECT_CODE)
  INNER JOIN SPECIALTIES S ON DR.SPECIALTY_ABBR = S.ABBREVIATION
  INNER JOIN LOOKUPS L ON L.TYPE = 'tipoDoc' AND DR.TYPE = L.CODE
  WHERE D.DOCNUMBER = DR.DOCNUMBER
  )
WHERE D.DOCNUMBER IN (SELECT DOCNUMBER FROM DOCUMENTS_RAW);