DROP SEQUENCE ROCA.MAT_PIPING_AP_SEQ;

CREATE SEQUENCE ROCA.MAT_PIPING_AP_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


ALTER TABLE ROCA.MAT_PIPING_AP
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.MAT_PIPING_AP CASCADE CONSTRAINTS;

CREATE TABLE ROCA.MAT_PIPING_AP
(
  ID             NUMBER(9)                      NOT NULL,
  PROJ_ID        CHAR(4 BYTE)                   NOT NULL,
  AREAID         VARCHAR2(50 BYTE),
  AREA           VARCHAR2(50 BYTE),
  LINE           VARCHAR2(62 BYTE),
  SERVICE        VARCHAR2(50 BYTE),
  TAG            VARCHAR2(24 BYTE),
  PIECE_MARK     VARCHAR2(50 BYTE),
  QUANTITY       FLOAT(126),
  TOTALQUANTITY  FLOAT(126)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ROCA.MAT_PIPING_AP_IX1 ON ROCA.MAT_PIPING_AP
(PROJ_ID, PIECE_MARK)
LOGGING
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX ROCA.MAT_PIPING_AP_PK ON ROCA.MAT_PIPING_AP
(ID)
LOGGING
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER ROCA.MAT_PIPING_AP_TRG
BEFORE INSERT
ON ROCA.MAT_PIPING_AP
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := MAT_PIPING_AP_SEQ.nextval;
END MAT_PIPING_AP_TRG;
/


ALTER TABLE ROCA.MAT_PIPING_AP ADD (
  CONSTRAINT MAT_PIPING_AP_PK
  PRIMARY KEY
  (ID)
  USING INDEX ROCA.MAT_PIPING_AP_PK
  ENABLE VALIDATE);


DROP SEQUENCE ROCA.MAT_PIPING_SEQ;

CREATE SEQUENCE ROCA.MAT_PIPING_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


ALTER TABLE ROCA.MAT_PIPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.MAT_PIPING CASCADE CONSTRAINTS;

CREATE TABLE ROCA.MAT_PIPING
(
  ID              NUMBER(9)                     NOT NULL,
  SPEC_TYPE       VARCHAR2(20 CHAR)             NOT NULL,
  SHORT_CODE      VARCHAR2(20 CHAR)             NOT NULL,
  COMMODITY_CODE  VARCHAR2(50 CHAR)             NOT NULL,
  OEP_CODE        VARCHAR2(20 CHAR)             NOT NULL,
  CLIENT_CODE     VARCHAR2(20 CHAR),
  GEOM1           VARCHAR2(20 CHAR)             NOT NULL,
  GEOM2           VARCHAR2(20 CHAR)             NOT NULL,
  GEOM3           VARCHAR2(20 CHAR)             NOT NULL,
  GEOM4           VARCHAR2(20 CHAR)             NOT NULL,
  THICK1          VARCHAR2(20 CHAR),
  THICK2          VARCHAR2(20 CHAR),
  IDENT_LAYOUT    VARCHAR2(100 CHAR)            NOT NULL,
  SHORT_DESC      VARCHAR2(255 CHAR)            NOT NULL,
  LONG_DESC       VARCHAR2(1000 CHAR)           NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ROCA.MAT_PIPING_PK ON ROCA.MAT_PIPING
(ID)
LOGGING
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX ROCA.MAT_PIPING_U01 ON ROCA.MAT_PIPING
(OEP_CODE)
LOGGING
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER ROCA.MAT_PIPING_TRG
BEFORE INSERT
ON ROCA.MAT_PIPING
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := MAT_PIPING_SEQ.nextval;
END MAT_PIPING_TRG;
/


ALTER TABLE ROCA.MAT_PIPING ADD (
  CONSTRAINT MAT_PIPING_PK
  PRIMARY KEY
  (ID)
  USING INDEX ROCA.MAT_PIPING_PK
  ENABLE VALIDATE,
  CONSTRAINT MAT_PIPING_U01
  UNIQUE (OEP_CODE)
  USING INDEX ROCA.MAT_PIPING_U01
  ENABLE VALIDATE);



DROP VIEW ROCA.V_MAT_PIPING;

/* Formatted on 08/06/2014 10:04:30 a.m. (QP5 v5.215.12089.38647) */
CREATE OR REPLACE FORCE VIEW ROCA.V_MAT_PIPING
(
   ID,
   PROJ_ID,
   SPEC_TYPE,
   COMMODITY_CODE,
   OEP_CODE,
   IDENT_LAYOUT,
   SHORT_DESC,
   LONG_DESC,
   QUANTITY,
   TOTALQUANTITY
)
AS
     SELECT M.ID,
            MAP.PROJ_ID,
            M.SPEC_TYPE,
            M.COMMODITY_CODE,
            M.OEP_CODE,
            M.IDENT_LAYOUT,
            M.SHORT_DESC,
            M.LONG_DESC,
            SUM (MAP.QUANTITY) QUANTITY,
            SUM (MAP.TOTALQUANTITY) TOTALQUANTITY
       FROM    MAT_PIPING_AP MAP
            INNER JOIN
               MAT_PIPING M
            ON MAP.PIECE_MARK = M.OEP_CODE
   GROUP BY M.ID,
            MAP.PROJ_ID,
            M.SPEC_TYPE,
            M.COMMODITY_CODE,
            M.OEP_CODE,
            M.IDENT_LAYOUT,
            M.SHORT_DESC,
            M.LONG_DESC;