--
-- Drop and Create Script 
--   Database Version          : 11.2.0.1.0 
--   Database Compatible Level : 11.2.0.1.0 
--   Toad Version              : 11.5.0.56 
--   DB Connect String         : ROCA 
--   Schema                    : ROCA 
--   Script Created by         : ROCA 
--   Script Created at         : 09/05/2014 15:33:42 
--   Physical Location         :  
--   Notes                     :  
--

-- Object Counts: 
--   Indexes: 23        Columns: 28         
--   Sequences: 8 
--   Tables: 19         Columns: 122        Constraints: 49     
--   Triggers: 8 
--   Views: 2           Columns: 12         


-- "Set define off" turns off substitution variables. 
Set define off; 

DROP SEQUENCE ROCA.DOCUMENTS_SEQ;

--
-- DOCUMENTS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.DOCUMENTS_SEQ
  START WITH 1541
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.MATERIALS_SEQ;

--
-- MATERIALS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.MATERIALS_SEQ
  START WITH 37339
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE ROCA.MATERIAL_LISTS_SEQ;

--
-- MATERIAL_LISTS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.MATERIAL_LISTS_SEQ
  START WITH 1881
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.ML_ITEMS_SEQ;

--
-- ML_ITEMS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.ML_ITEMS_SEQ
  START WITH 3481
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.TAGGABLE_ATTRIBUTES_SEQ;

--
-- TAGGABLE_ATTRIBUTES_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.TAGGABLE_ATTRIBUTES_SEQ
  START WITH 5681
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.TAGGABLE_TYPES_SEQ;

--
-- TAGGABLE_TYPES_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.TAGGABLE_TYPES_SEQ
  START WITH 2381
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.TIMESHEETS_SEQ;

--
-- TIMESHEETS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.TIMESHEETS_SEQ
  START WITH 121
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.TIMESHEET_ITEMS_SEQ;

--
-- TIMESHEET_ITEMS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.TIMESHEET_ITEMS_SEQ
  START WITH 401
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP TABLE ROCA.DOCUMENTS_RAW CASCADE CONSTRAINTS PURGE;

--
-- DOCUMENTS_RAW  (Table) 
--
CREATE TABLE ROCA.DOCUMENTS_RAW
(
  PROJECT_CODE     VARCHAR2(20 CHAR)            NOT NULL,
  SUBPROJECT_CODE  VARCHAR2(20 CHAR)            NOT NULL,
  SPECIALTY_ABBR   VARCHAR2(10 CHAR)            NOT NULL,
  TYPE             VARCHAR2(10 CHAR)            NOT NULL,
  DOCNUMBER        VARCHAR2(50 CHAR)            NOT NULL,
  TITLE            VARCHAR2(150 CHAR)           NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


DROP TABLE ROCA.MAT_EI_RAW CASCADE CONSTRAINTS PURGE;

--
-- MAT_EI_RAW  (Table) 
--
CREATE TABLE ROCA.MAT_EI_RAW
(
  PARTE          VARCHAR2(100 BYTE),
  IDENT_OEP      VARCHAR2(50 BYTE),
  GEOMETRIA      VARCHAR2(100 BYTE),
  INPUT_1        VARCHAR2(20 BYTE),
  INPUT_2        VARCHAR2(20 BYTE),
  INPUT_3        VARCHAR2(20 BYTE),
  INPUT_4        VARCHAR2(20 BYTE),
  COMMODITY_OEP  VARCHAR2(50 BYTE),
  NLS            VARCHAR2(10 BYTE),
  LAYOUT_CURTO   VARCHAR2(1000 BYTE),
  LAYOUT_LONGO   VARCHAR2(1500 BYTE),
  SEQ1           VARCHAR2(500 BYTE),
  SEQ2           VARCHAR2(500 BYTE),
  SEQ3           VARCHAR2(500 BYTE),
  SEQ4           VARCHAR2(500 BYTE),
  SEQ5           VARCHAR2(500 BYTE),
  SEQ6           VARCHAR2(500 BYTE),
  SEQ7           VARCHAR2(500 BYTE),
  SEQ8           VARCHAR2(500 BYTE),
  SEQ9           VARCHAR2(500 BYTE),
  SEQ10          VARCHAR2(500 BYTE),
  SEQ11          VARCHAR2(500 BYTE),
  SEQ12          VARCHAR2(500 BYTE),
  SEQ13          VARCHAR2(500 BYTE),
  SEQ14          VARCHAR2(500 BYTE),
  SEQ15          VARCHAR2(500 BYTE),
  SEQ16          VARCHAR2(500 BYTE),
  SEQ17          VARCHAR2(500 BYTE),
  SEQ18          VARCHAR2(500 BYTE),
  SEQ19          VARCHAR2(500 BYTE),
  SEQ20          VARCHAR2(500 BYTE),
  SEQ21          VARCHAR2(500 BYTE),
  SEQ22          VARCHAR2(500 BYTE),
  SEQ23          VARCHAR2(500 BYTE),
  SEQ24          VARCHAR2(500 BYTE),
  SEQ25          VARCHAR2(500 BYTE)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.MATERIALS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.MATERIALS CASCADE CONSTRAINTS PURGE;

--
-- MATERIALS  (Table) 
--
CREATE TABLE ROCA.MATERIALS
(
  MATERIAL_ID  NUMBER(9)                        NOT NULL,
  DESCRIPTION  VARCHAR2(100 BYTE)               NOT NULL,
  IDENT_CODE   VARCHAR2(50 BYTE)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.UNITS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.UNITS CASCADE CONSTRAINTS PURGE;

--
-- UNITS  (Table) 
--
CREATE TABLE ROCA.UNITS
(
  UNIT_ID       NUMBER(9)                       NOT NULL,
  ABBREVIATION  VARCHAR2(20 BYTE)               NOT NULL,
  NAME          VARCHAR2(50 BYTE)               NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.SPECIALTIES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.SPECIALTIES CASCADE CONSTRAINTS PURGE;

--
-- SPECIALTIES  (Table) 
--
CREATE TABLE ROCA.SPECIALTIES
(
  SPECIALTY_ID  NUMBER(9)                       NOT NULL,
  ABBREVIATION  VARCHAR2(10 BYTE)               NOT NULL,
  NAME          VARCHAR2(50 BYTE)               NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.EIMATERIALS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.EIMATERIALS CASCADE CONSTRAINTS PURGE;

--
-- EIMATERIALS  (Table) 
--
CREATE TABLE ROCA.EIMATERIALS
(
  MATERIAL_ID  NUMBER(9)                        NOT NULL,
  POWER        VARCHAR2(100 BYTE)               NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.PMATERIALS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.PMATERIALS CASCADE CONSTRAINTS PURGE;

--
-- PMATERIALS  (Table) 
--
CREATE TABLE ROCA.PMATERIALS
(
  MATERIAL_ID  NUMBER(9)                        NOT NULL,
  LENGHT       FLOAT(126)                       NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.USERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.USERS CASCADE CONSTRAINTS PURGE;

--
-- USERS  (Table) 
--
CREATE TABLE ROCA.USERS
(
  ID         NUMBER(9),
  USER_NAME  VARCHAR2(50 BYTE)                  NOT NULL,
  NAME       VARCHAR2(50 BYTE)                  NOT NULL,
  LAST_NAME  VARCHAR2(50 BYTE)                  NOT NULL,
  MAIL       VARCHAR2(50 BYTE)                  NOT NULL,
  ROLES      VARCHAR2(100 BYTE),
  INITIALS   VARCHAR2(10 BYTE)                  NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.PROJECTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.PROJECTS CASCADE CONSTRAINTS PURGE;

--
-- PROJECTS  (Table) 
--
CREATE TABLE ROCA.PROJECTS
(
  PROJECT_ID       NUMBER(9)                    NOT NULL,
  NAME             VARCHAR2(50 BYTE)            NOT NULL,
  CODE             VARCHAR2(20 CHAR)            NOT NULL,
  SHORT_NAME       VARCHAR2(50 CHAR)            NOT NULL,
  SUBPROJECT_TYPE  VARCHAR2(50 CHAR),
  PARENT_ID        NUMBER(9)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.USER_SPECIALTY
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.USER_SPECIALTY CASCADE CONSTRAINTS PURGE;

--
-- USER_SPECIALTY  (Table) 
--
CREATE TABLE ROCA.USER_SPECIALTY
(
  USER_ID       NUMBER(9)                       NOT NULL,
  SPECIALTY_ID  NUMBER(9)                       NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.MATERIAL_LISTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.MATERIAL_LISTS CASCADE CONSTRAINTS PURGE;

--
-- MATERIAL_LISTS  (Table) 
--
CREATE TABLE ROCA.MATERIAL_LISTS
(
  ML_ID           NUMBER(9)                     NOT NULL,
  DOC_NUMBER      VARCHAR2(50 BYTE)             NOT NULL,
  TITLE           VARCHAR2(100 BYTE)            NOT NULL,
  SPECIALTY_ID    NUMBER(9)                     NOT NULL,
  REVISION        VARCHAR2(5 BYTE)              NOT NULL,
  PREV_REV_ML_ID  NUMBER(9),
  CREATOR_ID      NUMBER(9)                     NOT NULL,
  CREATED_ON      DATE                          NOT NULL,
  UPDATER_ID      NUMBER(9),
  UPDATED_ON      DATE,
  REVISOR_ID      NUMBER(9),
  APPROVER_ID     NUMBER(9),
  PROJECT_ID      NUMBER(9)                     NOT NULL,
  STATUS          NUMBER(3)                     NOT NULL,
  DELETED         NUMBER(1)                     NOT NULL,
  PURPOSE         VARCHAR2(200 BYTE)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.ML_ITEMS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.ML_ITEMS CASCADE CONSTRAINTS PURGE;

--
-- ML_ITEMS  (Table) 
--
CREATE TABLE ROCA.ML_ITEMS
(
  ML_ITEM_ID     NUMBER(9)                      NOT NULL,
  ML_ID          NUMBER(9)                      NOT NULL,
  MATERIAL_ID    NUMBER(9)                      NOT NULL,
  QUANTITY       FLOAT(126)                     NOT NULL,
  QUANTITY_PREV  FLOAT(126)                     NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.LOOKUPS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.LOOKUPS CASCADE CONSTRAINTS PURGE;

--
-- LOOKUPS  (Table) 
--
CREATE TABLE ROCA.LOOKUPS
(
  LOOKUP_ID  NUMBER(9)                          NOT NULL,
  TYPE       VARCHAR2(50 CHAR)                  NOT NULL,
  CODE       VARCHAR2(50 CHAR)                  NOT NULL,
  VALUE      VARCHAR2(200 CHAR)                 NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.EIMATERIAL_DETAILS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.EIMATERIAL_DETAILS CASCADE CONSTRAINTS PURGE;

--
-- EIMATERIAL_DETAILS  (Table) 
--
CREATE TABLE ROCA.EIMATERIAL_DETAILS
(
  MATERIAL_ID       NUMBER(9)                   NOT NULL,
  LONG_DESCRIPTION  VARCHAR2(2000 BYTE)         NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.TAGGABLE_TYPES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.TAGGABLE_TYPES CASCADE CONSTRAINTS PURGE;

--
-- TAGGABLE_TYPES  (Table) 
--
CREATE TABLE ROCA.TAGGABLE_TYPES
(
  TAGGABLE_TYPE_ID  NUMBER(9)                   NOT NULL,
  SPECIALTY_ID      NUMBER(9)                   NOT NULL,
  PARENT_ID         NUMBER(9),
  NAME              VARCHAR2(50 BYTE)           NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.TAGGABLE_ATTRIBUTES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.TAGGABLE_ATTRIBUTES CASCADE CONSTRAINTS PURGE;

--
-- TAGGABLE_ATTRIBUTES  (Table) 
--
CREATE TABLE ROCA.TAGGABLE_ATTRIBUTES
(
  TAGGABLE_ATTRIBUTE_ID  NUMBER(9)              NOT NULL,
  TAGGABLE_TYPE_ID       NUMBER(9)              NOT NULL,
  NAME                   NVARCHAR2(50)          NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.DOCUMENTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.DOCUMENTS CASCADE CONSTRAINTS PURGE;

--
-- DOCUMENTS  (Table) 
--
CREATE TABLE ROCA.DOCUMENTS
(
  ID            NUMBER(9)                       NOT NULL,
  PROJECT_ID    NUMBER(9)                       NOT NULL,
  SPECIALTY_ID  NUMBER(9)                       NOT NULL,
  TYPE_ID       NUMBER(9)                       NOT NULL,
  DOCNUMBER     VARCHAR2(50 CHAR)               NOT NULL,
  TITLE         VARCHAR2(150 CHAR)              NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.TIMESHEETS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.TIMESHEETS CASCADE CONSTRAINTS PURGE;

--
-- TIMESHEETS  (Table) 
--
CREATE TABLE ROCA.TIMESHEETS
(
  ID            NUMBER(9)                       NOT NULL,
  USER_ID       NUMBER(9)                       NOT NULL,
  LEADER_ID     NUMBER(9),
  SPECIALTY_ID  NUMBER(9)                       NOT NULL,
  CONTROL_DATE  DATE                            NOT NULL,
  STATUS        NUMBER(3)                       NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.TIMESHEET_ITEMS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.TIMESHEET_ITEMS CASCADE CONSTRAINTS PURGE;

--
-- TIMESHEET_ITEMS  (Table) 
--
CREATE TABLE ROCA.TIMESHEET_ITEMS
(
  ID             NUMBER(9)                      NOT NULL,
  TIMESHEET_ID   NUMBER(9)                      NOT NULL,
  SUBPROJECT_ID  NUMBER(9)                      NOT NULL,
  DOCUMENT_ID    NUMBER(9),
  TASK_ID        NUMBER(9),
  HOURS          NUMBER(2)                      NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


--
-- SPECIALTIES_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.SPECIALTIES_PK ON ROCA.SPECIALTIES
(SPECIALTY_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- IDENT_CODE_IX  (Index) 
--
CREATE UNIQUE INDEX ROCA.IDENT_CODE_IX ON ROCA.MATERIALS
(IDENT_CODE)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- EIMATERIALS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.EIMATERIALS_PK ON ROCA.EIMATERIALS
(MATERIAL_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- EIMATERIAL_DETAILS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.EIMATERIAL_DETAILS_PK ON ROCA.EIMATERIAL_DETAILS
(MATERIAL_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- DOCUMENTS_RAW_U01  (Index) 
--
CREATE UNIQUE INDEX ROCA.DOCUMENTS_RAW_U01 ON ROCA.DOCUMENTS_RAW
(DOCNUMBER)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- MATERIAL_LISTS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.MATERIAL_LISTS_PK ON ROCA.MATERIAL_LISTS
(ML_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- USER_SPECIALTY_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.USER_SPECIALTY_PK ON ROCA.USER_SPECIALTY
(USER_ID, SPECIALTY_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- LOOKUPS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.LOOKUPS_PK ON ROCA.LOOKUPS
(LOOKUP_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- LOOKUPS_U01  (Index) 
--
CREATE UNIQUE INDEX ROCA.LOOKUPS_U01 ON ROCA.LOOKUPS
(TYPE, CODE)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- DOCUMENTS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.DOCUMENTS_PK ON ROCA.DOCUMENTS
(ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- DOCUMENTS_U01  (Index) 
--
CREATE UNIQUE INDEX ROCA.DOCUMENTS_U01 ON ROCA.DOCUMENTS
(PROJECT_ID, DOCNUMBER)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- MATERIALS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.MATERIALS_PK ON ROCA.MATERIALS
(MATERIAL_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- TAGGABLE_TYPES_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.TAGGABLE_TYPES_PK ON ROCA.TAGGABLE_TYPES
(TAGGABLE_TYPE_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- UNITS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.UNITS_PK ON ROCA.UNITS
(UNIT_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- PROJECTS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.PROJECTS_PK ON ROCA.PROJECTS
(PROJECT_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- ML_ITEMS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.ML_ITEMS_PK ON ROCA.ML_ITEMS
(ML_ITEM_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- IX_USERNAME  (Index) 
--
CREATE UNIQUE INDEX ROCA.IX_USERNAME ON ROCA.USERS
(USER_NAME)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- USERS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.USERS_PK ON ROCA.USERS
(ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- TIMESHEET_ITEMS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.TIMESHEET_ITEMS_PK ON ROCA.TIMESHEET_ITEMS
(ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- TAGGABLE_ATTRIBUTES_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.TAGGABLE_ATTRIBUTES_PK ON ROCA.TAGGABLE_ATTRIBUTES
(TAGGABLE_ATTRIBUTE_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- TIMESHEETS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.TIMESHEETS_PK ON ROCA.TIMESHEETS
(ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- TIMESHEETS_U01  (Index) 
--
CREATE UNIQUE INDEX ROCA.TIMESHEETS_U01 ON ROCA.TIMESHEETS
(USER_ID, SPECIALTY_ID, CONTROL_DATE)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- PMATERIALS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.PMATERIALS_PK ON ROCA.PMATERIALS
(MATERIAL_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


DROP VIEW ROCA.V_PROJECTS;

--
-- V_PROJECTS  (View) 
--
CREATE OR REPLACE FORCE VIEW ROCA.V_PROJECTS
(PROJECT_ID, CODE, SUBPROJECT_CODE, NAME, SUBPROJECT_NAME)
AS 
SELECT S.PROJECT_ID, P.CODE, S.CODE SUBPROJECT_CODE, P.NAME, S.NAME SUBPROJECT_NAME FROM
PROJECTS P INNER JOIN PROJECTS S ON P.PROJECT_ID = S.PARENT_ID
WHERE P.PARENT_ID IS NULL
UNION
SELECT P2.PROJECT_ID, P2.CODE, NULL, P2.NAME, NULL
FROM PROJECTS P2
WHERE P2.PARENT_ID IS NULL AND NOT EXISTS (SELECT * FROM PROJECTS P3 WHERE P3.PARENT_ID = P2.PROJECT_ID);


--
-- MATERIAL_LISTS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.MATERIAL_LISTS_TRG
BEFORE INSERT
ON ROCA.MATERIAL_LISTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ML_ID
  :new.ML_ID := MATERIAL_LISTS_SEQ.nextval;
END MATERIAL_LISTS_TRG;
/


--
-- ML_ITEMS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.ML_ITEMS_TRG
BEFORE INSERT
ON ROCA.ML_ITEMS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ML_ITEM_ID
  :new.ML_ITEM_ID := ML_ITEMS_SEQ.nextval;
END ML_ITEMS_TRG;
/


--
-- MATERIALS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.MATERIALS_TRG
BEFORE INSERT
ON ROCA.MATERIALS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column MATERIAL_ID
  :new.MATERIAL_ID := MATERIALS_SEQ.nextval;
END MATERIALS_TRG;
/


--
-- TAGGABLE_ATTRIBUTES_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.TAGGABLE_ATTRIBUTES_TRG
BEFORE INSERT
ON ROCA.TAGGABLE_ATTRIBUTES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column TAGGABLE_ATTRIBUTE_ID
  :new.TAGGABLE_ATTRIBUTE_ID := TAGGABLE_ATTRIBUTES_SEQ.nextval;
END TAGGABLE_ATTRIBUTES_TRG;
/


--
-- TAGGABLE_TYPES_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.TAGGABLE_TYPES_TRG
BEFORE INSERT
ON ROCA.TAGGABLE_TYPES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column TAGGABLE_TYPE_ID
  :new.TAGGABLE_TYPE_ID := TAGGABLE_TYPES_SEQ.nextval;
END TAGGABLE_TYPES_TRG;
/


--
-- TIMESHEETS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.TIMESHEETS_TRG
BEFORE INSERT
ON ROCA.TIMESHEETS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := TIMESHEETS_SEQ.nextval;
END TIMESHEETS_TRG;
/


--
-- DOCUMENTS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.DOCUMENTS_TRG
BEFORE INSERT
ON ROCA.DOCUMENTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := DOCUMENTS_SEQ.nextval;
END DOCUMENTS_TRG;
/


--
-- TIMESHEET_ITEMS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.TIMESHEET_ITEMS_TRG
BEFORE INSERT
ON ROCA.TIMESHEET_ITEMS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := TIMESHEET_ITEMS_SEQ.nextval;
END TIMESHEET_ITEMS_TRG;
/


DROP VIEW ROCA.V_DOCUMENTS;

--
-- V_DOCUMENTS  (View) 
--
CREATE OR REPLACE FORCE VIEW ROCA.V_DOCUMENTS
(ID, PROJECT_ID, PROJECT_NAME, SUBPROJECT_NAME, TYPE, 
 DOCNUMBER, TITLE)
AS 
SELECT D.ID, D.PROJECT_ID, P.NAME PROJECT_NAME, P.SUBPROJECT_NAME, L.CODE TYPE, D.DOCNUMBER, D.TITLE
  FROM DOCUMENTS D
  INNER JOIN V_PROJECTS P ON D.PROJECT_ID = P.PROJECT_ID
  INNER JOIN LOOKUPS L ON D.TYPE_ID = L.LOOKUP_ID;


-- 
-- Non Foreign Key Constraints for Table DOCUMENTS_RAW 
-- 
ALTER TABLE ROCA.DOCUMENTS_RAW ADD (
  CONSTRAINT DOCUMENTS_RAW_U01
  UNIQUE (DOCNUMBER)
  USING INDEX ROCA.DOCUMENTS_RAW_U01
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table MATERIALS 
-- 
ALTER TABLE ROCA.MATERIALS ADD (
  CONSTRAINT MATERIALS_PK
  PRIMARY KEY
  (MATERIAL_ID)
  USING INDEX ROCA.MATERIALS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table UNITS 
-- 
ALTER TABLE ROCA.UNITS ADD (
  CONSTRAINT UNITS_PK
  PRIMARY KEY
  (UNIT_ID)
  USING INDEX ROCA.UNITS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table SPECIALTIES 
-- 
ALTER TABLE ROCA.SPECIALTIES ADD (
  CONSTRAINT SPECIALTIES_PK
  PRIMARY KEY
  (SPECIALTY_ID)
  USING INDEX ROCA.SPECIALTIES_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table EIMATERIALS 
-- 
ALTER TABLE ROCA.EIMATERIALS ADD (
  CONSTRAINT EIMATERIALS_PK
  PRIMARY KEY
  (MATERIAL_ID)
  USING INDEX ROCA.EIMATERIALS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table PMATERIALS 
-- 
ALTER TABLE ROCA.PMATERIALS ADD (
  CONSTRAINT PMATERIALS_PK
  PRIMARY KEY
  (MATERIAL_ID)
  USING INDEX ROCA.PMATERIALS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table USERS 
-- 
ALTER TABLE ROCA.USERS ADD (
  CONSTRAINT USERS_PK
  PRIMARY KEY
  (ID)
  USING INDEX ROCA.USERS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table PROJECTS 
-- 
ALTER TABLE ROCA.PROJECTS ADD (
  CONSTRAINT PROJECTS_PK
  PRIMARY KEY
  (PROJECT_ID)
  USING INDEX ROCA.PROJECTS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table USER_SPECIALTY 
-- 
ALTER TABLE ROCA.USER_SPECIALTY ADD (
  CONSTRAINT USER_SPECIALTY_PK
  PRIMARY KEY
  (USER_ID, SPECIALTY_ID)
  USING INDEX ROCA.USER_SPECIALTY_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table MATERIAL_LISTS 
-- 
ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_PK
  PRIMARY KEY
  (ML_ID)
  USING INDEX ROCA.MATERIAL_LISTS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table ML_ITEMS 
-- 
ALTER TABLE ROCA.ML_ITEMS ADD (
  CONSTRAINT ML_ITEMS_PK
  PRIMARY KEY
  (ML_ITEM_ID)
  USING INDEX ROCA.ML_ITEMS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table LOOKUPS 
-- 
ALTER TABLE ROCA.LOOKUPS ADD (
  CONSTRAINT LOOKUPS_PK
  PRIMARY KEY
  (LOOKUP_ID)
  USING INDEX ROCA.LOOKUPS_PK
  ENABLE VALIDATE);

ALTER TABLE ROCA.LOOKUPS ADD (
  CONSTRAINT LOOKUPS_U01
  UNIQUE (TYPE, CODE)
  USING INDEX ROCA.LOOKUPS_U01
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table EIMATERIAL_DETAILS 
-- 
ALTER TABLE ROCA.EIMATERIAL_DETAILS ADD (
  CONSTRAINT EIMATERIAL_DETAILS_PK
  PRIMARY KEY
  (MATERIAL_ID)
  USING INDEX ROCA.EIMATERIAL_DETAILS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table TAGGABLE_TYPES 
-- 
ALTER TABLE ROCA.TAGGABLE_TYPES ADD (
  CONSTRAINT TAGGABLE_TYPES_PK
  PRIMARY KEY
  (TAGGABLE_TYPE_ID)
  USING INDEX ROCA.TAGGABLE_TYPES_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table TAGGABLE_ATTRIBUTES 
-- 
ALTER TABLE ROCA.TAGGABLE_ATTRIBUTES ADD (
  CONSTRAINT TAGGABLE_ATTRIBUTES_PK
  PRIMARY KEY
  (TAGGABLE_ATTRIBUTE_ID)
  USING INDEX ROCA.TAGGABLE_ATTRIBUTES_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table DOCUMENTS 
-- 
ALTER TABLE ROCA.DOCUMENTS ADD (
  CONSTRAINT DOCUMENTS_PK
  PRIMARY KEY
  (ID)
  USING INDEX ROCA.DOCUMENTS_PK
  ENABLE VALIDATE);

ALTER TABLE ROCA.DOCUMENTS ADD (
  CONSTRAINT DOCUMENTS_U01
  UNIQUE (PROJECT_ID, DOCNUMBER)
  USING INDEX ROCA.DOCUMENTS_U01
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table TIMESHEETS 
-- 
ALTER TABLE ROCA.TIMESHEETS ADD (
  CONSTRAINT TIMESHEETS_PK
  PRIMARY KEY
  (ID)
  USING INDEX ROCA.TIMESHEETS_PK
  ENABLE VALIDATE);

ALTER TABLE ROCA.TIMESHEETS ADD (
  CONSTRAINT TIMESHEETS_U01
  UNIQUE (USER_ID, SPECIALTY_ID, CONTROL_DATE)
  USING INDEX ROCA.TIMESHEETS_U01
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table TIMESHEET_ITEMS 
-- 
ALTER TABLE ROCA.TIMESHEET_ITEMS ADD (
  CONSTRAINT TIMESHEET_ITEMS_PK
  PRIMARY KEY
  (ID)
  USING INDEX ROCA.TIMESHEET_ITEMS_PK
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table EIMATERIALS 
-- 
ALTER TABLE ROCA.EIMATERIALS ADD (
  CONSTRAINT EIMATERIALS_FK1 
  FOREIGN KEY (MATERIAL_ID) 
  REFERENCES ROCA.MATERIALS (MATERIAL_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table PMATERIALS 
-- 
ALTER TABLE ROCA.PMATERIALS ADD (
  CONSTRAINT PMATERIALS_FK1 
  FOREIGN KEY (MATERIAL_ID) 
  REFERENCES ROCA.MATERIALS (MATERIAL_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table PROJECTS 
-- 
ALTER TABLE ROCA.PROJECTS ADD (
  CONSTRAINT PROJECTS_FK1 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES ROCA.PROJECTS (PROJECT_ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table USER_SPECIALTY 
-- 
ALTER TABLE ROCA.USER_SPECIALTY ADD (
  CONSTRAINT USER_SPECIALTY_FK2 
  FOREIGN KEY (SPECIALTY_ID) 
  REFERENCES ROCA.SPECIALTIES (SPECIALTY_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.USER_SPECIALTY ADD (
  CONSTRAINT USER_SPECIALTY_FK1 
  FOREIGN KEY (USER_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table MATERIAL_LISTS 
-- 
ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK3 
  FOREIGN KEY (SPECIALTY_ID) 
  REFERENCES ROCA.SPECIALTIES (SPECIALTY_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK4 
  FOREIGN KEY (CREATOR_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK5 
  FOREIGN KEY (UPDATER_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK6 
  FOREIGN KEY (REVISOR_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK7 
  FOREIGN KEY (APPROVER_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK8 
  FOREIGN KEY (PROJECT_ID) 
  REFERENCES ROCA.PROJECTS (PROJECT_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK2 
  FOREIGN KEY (PREV_REV_ML_ID) 
  REFERENCES ROCA.MATERIAL_LISTS (ML_ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table ML_ITEMS 
-- 
ALTER TABLE ROCA.ML_ITEMS ADD (
  CONSTRAINT ML_ITEMS_FK2 
  FOREIGN KEY (MATERIAL_ID) 
  REFERENCES ROCA.MATERIALS (MATERIAL_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.ML_ITEMS ADD (
  CONSTRAINT ML_ITEMS_FK1 
  FOREIGN KEY (ML_ID) 
  REFERENCES ROCA.MATERIAL_LISTS (ML_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table EIMATERIAL_DETAILS 
-- 
ALTER TABLE ROCA.EIMATERIAL_DETAILS ADD (
  CONSTRAINT EIMATERIAL_DETAILSFK1 
  FOREIGN KEY (MATERIAL_ID) 
  REFERENCES ROCA.EIMATERIALS (MATERIAL_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table TAGGABLE_TYPES 
-- 
ALTER TABLE ROCA.TAGGABLE_TYPES ADD (
  CONSTRAINT TAGGABLE_TYPES_FK1 
  FOREIGN KEY (SPECIALTY_ID) 
  REFERENCES ROCA.SPECIALTIES (SPECIALTY_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.TAGGABLE_TYPES ADD (
  CONSTRAINT TAGGABLE_TYPES_FK2 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES ROCA.TAGGABLE_TYPES (TAGGABLE_TYPE_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table TAGGABLE_ATTRIBUTES 
-- 
ALTER TABLE ROCA.TAGGABLE_ATTRIBUTES ADD (
  CONSTRAINT TAGGABLE_ATTRIBUTES_FK1 
  FOREIGN KEY (TAGGABLE_TYPE_ID) 
  REFERENCES ROCA.TAGGABLE_TYPES (TAGGABLE_TYPE_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table DOCUMENTS 
-- 
ALTER TABLE ROCA.DOCUMENTS ADD (
  CONSTRAINT DOCUMENTS_FK2 
  FOREIGN KEY (SPECIALTY_ID) 
  REFERENCES ROCA.SPECIALTIES (SPECIALTY_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.DOCUMENTS ADD (
  CONSTRAINT DOCUMENTS_FK1 
  FOREIGN KEY (PROJECT_ID) 
  REFERENCES ROCA.PROJECTS (PROJECT_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.DOCUMENTS ADD (
  CONSTRAINT DOCUMENTS_FK3 
  FOREIGN KEY (TYPE_ID) 
  REFERENCES ROCA.LOOKUPS (LOOKUP_ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table TIMESHEETS 
-- 
ALTER TABLE ROCA.TIMESHEETS ADD (
  CONSTRAINT TIMESHEETS_FK3 
  FOREIGN KEY (SPECIALTY_ID) 
  REFERENCES ROCA.SPECIALTIES (SPECIALTY_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.TIMESHEETS ADD (
  CONSTRAINT TIMESHEETS_FK1 
  FOREIGN KEY (USER_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.TIMESHEETS ADD (
  CONSTRAINT TIMESHEETS_FK2 
  FOREIGN KEY (LEADER_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table TIMESHEET_ITEMS 
-- 
ALTER TABLE ROCA.TIMESHEET_ITEMS ADD (
  CONSTRAINT TIMESHEET_ITEMS_FK4 
  FOREIGN KEY (SUBPROJECT_ID) 
  REFERENCES ROCA.PROJECTS (PROJECT_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.TIMESHEET_ITEMS ADD (
  CONSTRAINT TIMESHEET_ITEMS_FK3 
  FOREIGN KEY (TASK_ID) 
  REFERENCES ROCA.LOOKUPS (LOOKUP_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.TIMESHEET_ITEMS ADD (
  CONSTRAINT TIMESHEET_ITEMS_FK2 
  FOREIGN KEY (DOCUMENT_ID) 
  REFERENCES ROCA.DOCUMENTS (ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.TIMESHEET_ITEMS ADD (
  CONSTRAINT TIMESHEET_ITEMS_FK1 
  FOREIGN KEY (TIMESHEET_ID) 
  REFERENCES ROCA.TIMESHEETS (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);