--
-- Drop and Create Script 
--   Database Version          : 11.2.0.1.0 
--   Database Compatible Level : 11.2.0.1.0 
--   Toad Version              : 11.5.0.56 
--   DB Connect String         : ROCA 
--   Schema                    : ROCA 
--   Script Created by         : ROCA 
--   Script Created at         : 13/02/2015 12:55:22 
--   Physical Location         :  
--   Notes                     :  
--

-- Object Counts: 
--   Indexes: 39        Columns: 48         
--   Sequences: 14 
--   Tables: 30         Columns: 187        Constraints: 72     
--   Triggers: 14 


-- "Set define off" turns off substitution variables. 
Set define off; 

DROP SEQUENCE ROCA.BAS_CODES_SEQ;

--
-- BAS_CODES_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.BAS_CODES_SEQ
  START WITH 3621
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.BAS_CODE_FIELDS_SEQ;

--
-- BAS_CODE_FIELDS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.BAS_CODE_FIELDS_SEQ
  START WITH 921
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.BAS_ELEMENTS_SEQ;

--
-- BAS_ELEMENTS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.BAS_ELEMENTS_SEQ
  START WITH 81
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.BAS_FIELD_DEFINITIONS_SEQ;

--
-- BAS_FIELD_DEFINITIONS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.BAS_FIELD_DEFINITIONS_SEQ
  START WITH 441
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.DOCUMENTS_SEQ;

--
-- DOCUMENTS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.DOCUMENTS_SEQ
  START WITH 4161
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.MATERIALS_SEQ;

--
-- MATERIALS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.MATERIALS_SEQ
  START WITH 44140
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE ROCA.MATERIAL_LISTS_SEQ;

--
-- MATERIAL_LISTS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.MATERIAL_LISTS_SEQ
  START WITH 2201
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.MAT_PIPING_AP_SEQ;

--
-- MAT_PIPING_AP_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.MAT_PIPING_AP_SEQ
  START WITH 32001
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.MAT_PIPING_SEQ;

--
-- MAT_PIPING_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.MAT_PIPING_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.ML_ITEMS_SEQ;

--
-- ML_ITEMS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.ML_ITEMS_SEQ
  START WITH 4061
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.TAGGABLE_ATTRIBUTES_SEQ;

--
-- TAGGABLE_ATTRIBUTES_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.TAGGABLE_ATTRIBUTES_SEQ
  START WITH 6801
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.TAGGABLE_TYPES_SEQ;

--
-- TAGGABLE_TYPES_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.TAGGABLE_TYPES_SEQ
  START WITH 2841
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.TIMESHEETS_SEQ;

--
-- TIMESHEETS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.TIMESHEETS_SEQ
  START WITH 2361
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE ROCA.TIMESHEET_ITEMS_SEQ;

--
-- TIMESHEET_ITEMS_SEQ  (Sequence) 
--
CREATE SEQUENCE ROCA.TIMESHEET_ITEMS_SEQ
  START WITH 11981
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP TABLE ROCA.DOCUMENTS_RAW CASCADE CONSTRAINTS PURGE;

--
-- DOCUMENTS_RAW  (Table) 
--
CREATE TABLE ROCA.DOCUMENTS_RAW
(
  PROJECT_CODE     VARCHAR2(20 CHAR)            NOT NULL,
  SUBPROJECT_CODE  VARCHAR2(20 CHAR)            NOT NULL,
  SPECIALTY_ABBR   VARCHAR2(10 CHAR)            NOT NULL,
  TYPE             VARCHAR2(10 CHAR)            NOT NULL,
  DOCNUMBER        VARCHAR2(50 CHAR)            NOT NULL,
  TITLE            VARCHAR2(150 CHAR)           NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


DROP TABLE ROCA.MAT_EI_RAW CASCADE CONSTRAINTS PURGE;

--
-- MAT_EI_RAW  (Table) 
--
CREATE TABLE ROCA.MAT_EI_RAW
(
  PARTE          VARCHAR2(100 BYTE),
  IDENT_OEP      VARCHAR2(50 BYTE),
  GEOMETRIA      VARCHAR2(100 BYTE),
  INPUT_1        VARCHAR2(20 BYTE),
  INPUT_2        VARCHAR2(20 BYTE),
  INPUT_3        VARCHAR2(20 BYTE),
  INPUT_4        VARCHAR2(20 BYTE),
  COMMODITY_OEP  VARCHAR2(50 BYTE),
  NLS            VARCHAR2(10 BYTE),
  LAYOUT_CURTO   VARCHAR2(1000 BYTE),
  LAYOUT_LONGO   VARCHAR2(1500 BYTE),
  SEQ1           VARCHAR2(500 BYTE),
  SEQ2           VARCHAR2(500 BYTE),
  SEQ3           VARCHAR2(500 BYTE),
  SEQ4           VARCHAR2(500 BYTE),
  SEQ5           VARCHAR2(500 BYTE),
  SEQ6           VARCHAR2(500 BYTE),
  SEQ7           VARCHAR2(500 BYTE),
  SEQ8           VARCHAR2(500 BYTE),
  SEQ9           VARCHAR2(500 BYTE),
  SEQ10          VARCHAR2(500 BYTE),
  SEQ11          VARCHAR2(500 BYTE),
  SEQ12          VARCHAR2(500 BYTE),
  SEQ13          VARCHAR2(500 BYTE),
  SEQ14          VARCHAR2(500 BYTE),
  SEQ15          VARCHAR2(500 BYTE),
  SEQ16          VARCHAR2(500 BYTE),
  SEQ17          VARCHAR2(500 BYTE),
  SEQ18          VARCHAR2(500 BYTE),
  SEQ19          VARCHAR2(500 BYTE),
  SEQ20          VARCHAR2(500 BYTE),
  SEQ21          VARCHAR2(500 BYTE),
  SEQ22          VARCHAR2(500 BYTE),
  SEQ23          VARCHAR2(500 BYTE),
  SEQ24          VARCHAR2(500 BYTE),
  SEQ25          VARCHAR2(500 BYTE)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.MATERIALS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.MATERIALS CASCADE CONSTRAINTS PURGE;

--
-- MATERIALS  (Table) 
--
CREATE TABLE ROCA.MATERIALS
(
  MATERIAL_ID  NUMBER(9)                        NOT NULL,
  DESCRIPTION  VARCHAR2(100 BYTE)               NOT NULL,
  IDENT_CODE   VARCHAR2(50 BYTE)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.UNITS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.UNITS CASCADE CONSTRAINTS PURGE;

--
-- UNITS  (Table) 
--
CREATE TABLE ROCA.UNITS
(
  UNIT_ID       NUMBER(9)                       NOT NULL,
  ABBREVIATION  VARCHAR2(20 BYTE)               NOT NULL,
  NAME          VARCHAR2(50 BYTE)               NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.SPECIALTIES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.SPECIALTIES CASCADE CONSTRAINTS PURGE;

--
-- SPECIALTIES  (Table) 
--
CREATE TABLE ROCA.SPECIALTIES
(
  SPECIALTY_ID  NUMBER(9)                       NOT NULL,
  ABBREVIATION  VARCHAR2(10 BYTE)               NOT NULL,
  NAME          VARCHAR2(50 BYTE)               NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.EIMATERIALS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.EIMATERIALS CASCADE CONSTRAINTS PURGE;

--
-- EIMATERIALS  (Table) 
--
CREATE TABLE ROCA.EIMATERIALS
(
  MATERIAL_ID  NUMBER(9)                        NOT NULL,
  POWER        VARCHAR2(100 BYTE)               NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.PMATERIALS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.PMATERIALS CASCADE CONSTRAINTS PURGE;

--
-- PMATERIALS  (Table) 
--
CREATE TABLE ROCA.PMATERIALS
(
  MATERIAL_ID  NUMBER(9)                        NOT NULL,
  LENGHT       FLOAT(126)                       NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.USERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.USERS CASCADE CONSTRAINTS PURGE;

--
-- USERS  (Table) 
--
CREATE TABLE ROCA.USERS
(
  ID         NUMBER(9),
  USER_NAME  VARCHAR2(50 BYTE)                  NOT NULL,
  NAME       VARCHAR2(50 BYTE)                  NOT NULL,
  LAST_NAME  VARCHAR2(50 BYTE)                  NOT NULL,
  MAIL       VARCHAR2(50 BYTE)                  NOT NULL,
  ROLES      VARCHAR2(100 BYTE),
  INITIALS   VARCHAR2(10 BYTE)                  NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.PROJECTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.PROJECTS CASCADE CONSTRAINTS PURGE;

--
-- PROJECTS  (Table) 
--
CREATE TABLE ROCA.PROJECTS
(
  PROJECT_ID       NUMBER(9)                    NOT NULL,
  NAME             VARCHAR2(50 BYTE)            NOT NULL,
  CODE             VARCHAR2(20 CHAR)            NOT NULL,
  SHORT_NAME       VARCHAR2(50 CHAR)            NOT NULL,
  SUBPROJECT_TYPE  VARCHAR2(50 CHAR),
  PARENT_ID        NUMBER(9)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.USER_SPECIALTY
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.USER_SPECIALTY CASCADE CONSTRAINTS PURGE;

--
-- USER_SPECIALTY  (Table) 
--
CREATE TABLE ROCA.USER_SPECIALTY
(
  USER_ID       NUMBER(9)                       NOT NULL,
  SPECIALTY_ID  NUMBER(9)                       NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.MATERIAL_LISTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.MATERIAL_LISTS CASCADE CONSTRAINTS PURGE;

--
-- MATERIAL_LISTS  (Table) 
--
CREATE TABLE ROCA.MATERIAL_LISTS
(
  ML_ID           NUMBER(9)                     NOT NULL,
  DOC_NUMBER      VARCHAR2(50 BYTE)             NOT NULL,
  TITLE           VARCHAR2(100 BYTE)            NOT NULL,
  SPECIALTY_ID    NUMBER(9)                     NOT NULL,
  REVISION        VARCHAR2(5 BYTE)              NOT NULL,
  PREV_REV_ML_ID  NUMBER(9),
  CREATOR_ID      NUMBER(9)                     NOT NULL,
  CREATED_ON      DATE                          NOT NULL,
  UPDATER_ID      NUMBER(9),
  UPDATED_ON      DATE,
  REVISOR_ID      NUMBER(9),
  APPROVER_ID     NUMBER(9),
  PROJECT_ID      NUMBER(9)                     NOT NULL,
  STATUS          NUMBER(3)                     NOT NULL,
  DELETED         NUMBER(1)                     NOT NULL,
  PURPOSE         VARCHAR2(200 BYTE)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.ML_ITEMS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.ML_ITEMS CASCADE CONSTRAINTS PURGE;

--
-- ML_ITEMS  (Table) 
--
CREATE TABLE ROCA.ML_ITEMS
(
  ML_ITEM_ID     NUMBER(9)                      NOT NULL,
  ML_ID          NUMBER(9)                      NOT NULL,
  MATERIAL_ID    NUMBER(9)                      NOT NULL,
  QUANTITY       FLOAT(126)                     NOT NULL,
  QUANTITY_PREV  FLOAT(126)                     NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.LOOKUPS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.LOOKUPS CASCADE CONSTRAINTS PURGE;

--
-- LOOKUPS  (Table) 
--
CREATE TABLE ROCA.LOOKUPS
(
  LOOKUP_ID  NUMBER(9)                          NOT NULL,
  TYPE       VARCHAR2(50 CHAR)                  NOT NULL,
  CODE       VARCHAR2(50 CHAR)                  NOT NULL,
  VALUE      VARCHAR2(500 CHAR)                 NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.EIMATERIAL_DETAILS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.EIMATERIAL_DETAILS CASCADE CONSTRAINTS PURGE;

--
-- EIMATERIAL_DETAILS  (Table) 
--
CREATE TABLE ROCA.EIMATERIAL_DETAILS
(
  MATERIAL_ID       NUMBER(9)                   NOT NULL,
  LONG_DESCRIPTION  VARCHAR2(2000 BYTE)         NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.TAGGABLE_TYPES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.TAGGABLE_TYPES CASCADE CONSTRAINTS PURGE;

--
-- TAGGABLE_TYPES  (Table) 
--
CREATE TABLE ROCA.TAGGABLE_TYPES
(
  TAGGABLE_TYPE_ID  NUMBER(9)                   NOT NULL,
  SPECIALTY_ID      NUMBER(9)                   NOT NULL,
  PARENT_ID         NUMBER(9),
  NAME              VARCHAR2(50 BYTE)           NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.TAGGABLE_ATTRIBUTES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.TAGGABLE_ATTRIBUTES CASCADE CONSTRAINTS PURGE;

--
-- TAGGABLE_ATTRIBUTES  (Table) 
--
CREATE TABLE ROCA.TAGGABLE_ATTRIBUTES
(
  TAGGABLE_ATTRIBUTE_ID  NUMBER(9)              NOT NULL,
  TAGGABLE_TYPE_ID       NUMBER(9)              NOT NULL,
  NAME                   NVARCHAR2(50)          NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   3
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.DOCUMENTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.DOCUMENTS CASCADE CONSTRAINTS PURGE;

--
-- DOCUMENTS  (Table) 
--
CREATE TABLE ROCA.DOCUMENTS
(
  ID            NUMBER(9)                       NOT NULL,
  PROJECT_ID    NUMBER(9)                       NOT NULL,
  SPECIALTY_ID  NUMBER(9)                       NOT NULL,
  TYPE_ID       NUMBER(9)                       NOT NULL,
  DOCNUMBER     VARCHAR2(50 CHAR)               NOT NULL,
  TITLE         VARCHAR2(150 CHAR)              NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.TIMESHEETS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.TIMESHEETS CASCADE CONSTRAINTS PURGE;

--
-- TIMESHEETS  (Table) 
--
CREATE TABLE ROCA.TIMESHEETS
(
  ID            NUMBER(9)                       NOT NULL,
  USER_ID       NUMBER(9)                       NOT NULL,
  LEADER_ID     NUMBER(9),
  SPECIALTY_ID  NUMBER(9)                       NOT NULL,
  CONTROL_DATE  DATE                            NOT NULL,
  STATUS        NUMBER(3)                       NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.TIMESHEET_ITEMS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.TIMESHEET_ITEMS CASCADE CONSTRAINTS PURGE;

--
-- TIMESHEET_ITEMS  (Table) 
--
CREATE TABLE ROCA.TIMESHEET_ITEMS
(
  ID             NUMBER(9)                      NOT NULL,
  TIMESHEET_ID   NUMBER(9)                      NOT NULL,
  SUBPROJECT_ID  NUMBER(9)                      NOT NULL,
  DOCUMENT_ID    NUMBER(9),
  TASK_ID        NUMBER(9),
  HOURS          NUMBER(2)                      NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.BAS_CODES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.BAS_CODES CASCADE CONSTRAINTS PURGE;

--
-- BAS_CODES  (Table) 
--
CREATE TABLE ROCA.BAS_CODES
(
  BAS_CODE_ID        NUMBER(9)                  NOT NULL,
  FIELD              VARCHAR2(50 CHAR)          NOT NULL,
  CODE               VARCHAR2(50 CHAR)          NOT NULL,
  DESCRIPTION        VARCHAR2(500 CHAR)         NOT NULL,
  SHORT_DESCRIPTION  VARCHAR2(500 CHAR)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.MAT_PIPING_AP
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.MAT_PIPING_AP CASCADE CONSTRAINTS PURGE;

--
-- MAT_PIPING_AP  (Table) 
--
CREATE TABLE ROCA.MAT_PIPING_AP
(
  ID             NUMBER(9)                      NOT NULL,
  PROJ_ID        CHAR(4 BYTE)                   NOT NULL,
  AREAID         VARCHAR2(50 BYTE),
  AREA           VARCHAR2(50 BYTE),
  LINE           VARCHAR2(62 BYTE),
  SERVICE        VARCHAR2(50 BYTE),
  TAG            VARCHAR2(24 BYTE),
  PIECE_MARK     VARCHAR2(50 BYTE),
  QUANTITY       FLOAT(126),
  TOTALQUANTITY  FLOAT(126)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.MAT_PIPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.MAT_PIPING CASCADE CONSTRAINTS PURGE;

--
-- MAT_PIPING  (Table) 
--
CREATE TABLE ROCA.MAT_PIPING
(
  ID              NUMBER(9)                     NOT NULL,
  SPEC_TYPE       VARCHAR2(20 CHAR)             NOT NULL,
  SHORT_CODE      VARCHAR2(20 CHAR)             NOT NULL,
  COMMODITY_CODE  VARCHAR2(50 CHAR)             NOT NULL,
  OEP_CODE        VARCHAR2(20 CHAR)             NOT NULL,
  CLIENT_CODE     VARCHAR2(20 CHAR),
  GEOM1           VARCHAR2(20 CHAR)             NOT NULL,
  GEOM2           VARCHAR2(20 CHAR)             NOT NULL,
  GEOM3           VARCHAR2(20 CHAR)             NOT NULL,
  GEOM4           VARCHAR2(20 CHAR)             NOT NULL,
  THICK1          VARCHAR2(20 CHAR),
  THICK2          VARCHAR2(20 CHAR),
  IDENT_LAYOUT    VARCHAR2(100 CHAR)            NOT NULL,
  SHORT_DESC      VARCHAR2(255 CHAR)            NOT NULL,
  LONG_DESC       VARCHAR2(1000 CHAR)           NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.BAS_ELEMENTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.BAS_ELEMENTS CASCADE CONSTRAINTS PURGE;

--
-- BAS_ELEMENTS  (Table) 
--
CREATE TABLE ROCA.BAS_ELEMENTS
(
  BAS_ELEMENT_ID       NUMBER(9)                NOT NULL,
  BAS_CLASS_ID         NUMBER(9)                NOT NULL,
  BAS_ELEMENT_TYPE_ID  NUMBER(9)                NOT NULL,
  FULL_CODE            VARCHAR2(50 CHAR)        NOT NULL,
  UNIT                 VARCHAR2(20 CHAR)        NOT NULL,
  OBSERVATIONS         VARCHAR2(1024 CHAR),
  WEIGHT               FLOAT(126)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


DROP TABLE ROCA.BAS_CODES_RAW CASCADE CONSTRAINTS PURGE;

--
-- BAS_CODES_RAW  (Table) 
--
CREATE TABLE ROCA.BAS_CODES_RAW
(
  FIELD              VARCHAR2(50 CHAR)          NOT NULL,
  CODE               VARCHAR2(50 CHAR)          NOT NULL,
  DESCRIPTION        VARCHAR2(500 CHAR)         NOT NULL,
  SHORT_DESCRIPTION  VARCHAR2(500 CHAR)
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.BAS_CLASSES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.BAS_CLASSES CASCADE CONSTRAINTS PURGE;

--
-- BAS_CLASSES  (Table) 
--
CREATE TABLE ROCA.BAS_CLASSES
(
  BAS_CLASS_ID  NUMBER(9)                       NOT NULL,
  NAME          VARCHAR2(200 CHAR)              NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.BAS_CLASS_ATTRIBUTES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.BAS_CLASS_ATTRIBUTES CASCADE CONSTRAINTS PURGE;

--
-- BAS_CLASS_ATTRIBUTES  (Table) 
--
CREATE TABLE ROCA.BAS_CLASS_ATTRIBUTES
(
  BAS_CLASS_ATTRIBUTE_ID  NUMBER(9)             NOT NULL,
  BAS_CLASS_ID            NUMBER(9)             NOT NULL,
  NAME                    VARCHAR2(50 CHAR)     NOT NULL,
  TYPE                    VARCHAR2(50 CHAR)     NOT NULL,
  PROPERTY                VARCHAR2(50 CHAR)     NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.BAS_ELEMENT_TYPES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.BAS_ELEMENT_TYPES CASCADE CONSTRAINTS PURGE;

--
-- BAS_ELEMENT_TYPES  (Table) 
--
CREATE TABLE ROCA.BAS_ELEMENT_TYPES
(
  BAS_ELEMENT_TYPE_ID  NUMBER(9)                NOT NULL,
  CODE                 VARCHAR2(20 CHAR)        NOT NULL,
  NAME                 VARCHAR2(200 CHAR)       NOT NULL,
  BAS_CLASS_ID         NUMBER(9)                NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


--
-- SPECIALTIES_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.SPECIALTIES_PK ON ROCA.SPECIALTIES
(SPECIALTY_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- BAS_CODES_RAW_U01  (Index) 
--
CREATE UNIQUE INDEX ROCA.BAS_CODES_RAW_U01 ON ROCA.BAS_CODES_RAW
(FIELD, CODE)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- IDENT_CODE_IX  (Index) 
--
CREATE UNIQUE INDEX ROCA.IDENT_CODE_IX ON ROCA.MATERIALS
(IDENT_CODE)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- EIMATERIALS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.EIMATERIALS_PK ON ROCA.EIMATERIALS
(MATERIAL_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- EIMATERIAL_DETAILS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.EIMATERIAL_DETAILS_PK ON ROCA.EIMATERIAL_DETAILS
(MATERIAL_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- DOCUMENTS_RAW_U01  (Index) 
--
CREATE UNIQUE INDEX ROCA.DOCUMENTS_RAW_U01 ON ROCA.DOCUMENTS_RAW
(DOCNUMBER)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- MATERIAL_LISTS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.MATERIAL_LISTS_PK ON ROCA.MATERIAL_LISTS
(ML_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- USER_SPECIALTY_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.USER_SPECIALTY_PK ON ROCA.USER_SPECIALTY
(USER_ID, SPECIALTY_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- LOOKUPS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.LOOKUPS_PK ON ROCA.LOOKUPS
(LOOKUP_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- LOOKUPS_U01  (Index) 
--
CREATE UNIQUE INDEX ROCA.LOOKUPS_U01 ON ROCA.LOOKUPS
(TYPE, CODE)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- DOCUMENTS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.DOCUMENTS_PK ON ROCA.DOCUMENTS
(ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- DOCUMENTS_U01  (Index) 
--
CREATE UNIQUE INDEX ROCA.DOCUMENTS_U01 ON ROCA.DOCUMENTS
(PROJECT_ID, DOCNUMBER)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- MATERIALS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.MATERIALS_PK ON ROCA.MATERIALS
(MATERIAL_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- TAGGABLE_TYPES_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.TAGGABLE_TYPES_PK ON ROCA.TAGGABLE_TYPES
(TAGGABLE_TYPE_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- UNITS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.UNITS_PK ON ROCA.UNITS
(UNIT_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- PROJECTS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.PROJECTS_PK ON ROCA.PROJECTS
(PROJECT_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- BAS_CODES_PK1  (Index) 
--
CREATE UNIQUE INDEX ROCA.BAS_CODES_PK1 ON ROCA.BAS_CODES
(BAS_CODE_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- BAS_CODES_U01  (Index) 
--
CREATE UNIQUE INDEX ROCA.BAS_CODES_U01 ON ROCA.BAS_CODES
(FIELD, CODE)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- ML_ITEMS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.ML_ITEMS_PK ON ROCA.ML_ITEMS
(ML_ITEM_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- BAS_CLASSES_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.BAS_CLASSES_PK ON ROCA.BAS_CLASSES
(BAS_CLASS_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- BAS_CLASS_ATTRIBUTES_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.BAS_CLASS_ATTRIBUTES_PK ON ROCA.BAS_CLASS_ATTRIBUTES
(BAS_CLASS_ATTRIBUTE_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- BAS_ELEMENT_TYPES_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.BAS_ELEMENT_TYPES_PK ON ROCA.BAS_ELEMENT_TYPES
(BAS_ELEMENT_TYPE_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- BAS_ELEMENT_TYPES_U01  (Index) 
--
CREATE UNIQUE INDEX ROCA.BAS_ELEMENT_TYPES_U01 ON ROCA.BAS_ELEMENT_TYPES
(CODE)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- PMATERIALS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.PMATERIALS_PK ON ROCA.PMATERIALS
(MATERIAL_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- IX_USERNAME  (Index) 
--
CREATE UNIQUE INDEX ROCA.IX_USERNAME ON ROCA.USERS
(USER_NAME)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- USERS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.USERS_PK ON ROCA.USERS
(ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   5
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- TIMESHEET_ITEMS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.TIMESHEET_ITEMS_PK ON ROCA.TIMESHEET_ITEMS
(ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- TAGGABLE_ATTRIBUTES_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.TAGGABLE_ATTRIBUTES_PK ON ROCA.TAGGABLE_ATTRIBUTES
(TAGGABLE_ATTRIBUTE_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- TIMESHEETS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.TIMESHEETS_PK ON ROCA.TIMESHEETS
(ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- TIMESHEETS_U01  (Index) 
--
CREATE UNIQUE INDEX ROCA.TIMESHEETS_U01 ON ROCA.TIMESHEETS
(USER_ID, SPECIALTY_ID, CONTROL_DATE)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- MAT_PIPING_AP_IX1  (Index) 
--
CREATE INDEX ROCA.MAT_PIPING_AP_IX1 ON ROCA.MAT_PIPING_AP
(PROJ_ID, PIECE_MARK)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- MAT_PIPING_AP_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.MAT_PIPING_AP_PK ON ROCA.MAT_PIPING_AP
(ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- MAT_PIPING_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.MAT_PIPING_PK ON ROCA.MAT_PIPING
(ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- MAT_PIPING_U01  (Index) 
--
CREATE UNIQUE INDEX ROCA.MAT_PIPING_U01 ON ROCA.MAT_PIPING
(OEP_CODE)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- BAS_ELEMENTS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.BAS_ELEMENTS_PK ON ROCA.BAS_ELEMENTS
(BAS_ELEMENT_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- MATERIAL_LISTS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.MATERIAL_LISTS_TRG
BEFORE INSERT
ON ROCA.MATERIAL_LISTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ML_ID
  :new.ML_ID := MATERIAL_LISTS_SEQ.nextval;
END MATERIAL_LISTS_TRG;
/


--
-- ML_ITEMS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.ML_ITEMS_TRG
BEFORE INSERT
ON ROCA.ML_ITEMS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ML_ITEM_ID
  :new.ML_ITEM_ID := ML_ITEMS_SEQ.nextval;
END ML_ITEMS_TRG;
/


--
-- MATERIALS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.MATERIALS_TRG
BEFORE INSERT
ON ROCA.MATERIALS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column MATERIAL_ID
  :new.MATERIAL_ID := MATERIALS_SEQ.nextval;
END MATERIALS_TRG;
/


--
-- TAGGABLE_ATTRIBUTES_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.TAGGABLE_ATTRIBUTES_TRG
BEFORE INSERT
ON ROCA.TAGGABLE_ATTRIBUTES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column TAGGABLE_ATTRIBUTE_ID
  :new.TAGGABLE_ATTRIBUTE_ID := TAGGABLE_ATTRIBUTES_SEQ.nextval;
END TAGGABLE_ATTRIBUTES_TRG;
/


--
-- TAGGABLE_TYPES_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.TAGGABLE_TYPES_TRG
BEFORE INSERT
ON ROCA.TAGGABLE_TYPES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column TAGGABLE_TYPE_ID
  :new.TAGGABLE_TYPE_ID := TAGGABLE_TYPES_SEQ.nextval;
END TAGGABLE_TYPES_TRG;
/


--
-- TIMESHEETS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.TIMESHEETS_TRG
BEFORE INSERT
ON ROCA.TIMESHEETS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := TIMESHEETS_SEQ.nextval;
END TIMESHEETS_TRG;
/


--
-- DOCUMENTS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.DOCUMENTS_TRG
BEFORE INSERT
ON ROCA.DOCUMENTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := DOCUMENTS_SEQ.nextval;
END DOCUMENTS_TRG;
/


--
-- TIMESHEET_ITEMS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.TIMESHEET_ITEMS_TRG
BEFORE INSERT
ON ROCA.TIMESHEET_ITEMS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := TIMESHEET_ITEMS_SEQ.nextval;
END TIMESHEET_ITEMS_TRG;
/


--
-- MAT_PIPING_AP_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.MAT_PIPING_AP_TRG
BEFORE INSERT
ON ROCA.MAT_PIPING_AP
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := MAT_PIPING_AP_SEQ.nextval;
END MAT_PIPING_AP_TRG;
/


--
-- MAT_PIPING_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.MAT_PIPING_TRG
BEFORE INSERT
ON ROCA.MAT_PIPING
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DISABLE
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := MAT_PIPING_SEQ.nextval;
END MAT_PIPING_TRG;
/


--
-- BAS_CODES_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.BAS_CODES_TRG
BEFORE INSERT
ON ROCA.BAS_CODES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column BAS_CODE_ID
  :new.BAS_CODE_ID := BAS_CODES_SEQ.nextval;
END BAS_CODES_TRG;
/


--
-- BAS_ELEMENTS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.BAS_ELEMENTS_TRG
BEFORE INSERT
ON ROCA.BAS_ELEMENTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column BAS_ELEMENT_ID
  :new.BAS_ELEMENT_ID := BAS_ELEMENTS_SEQ.nextval;
END BAS_ELEMENTS_TRG;
/


ALTER TABLE ROCA.BAS_ELEMENT_TYPE_SPECIALTY
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.BAS_ELEMENT_TYPE_SPECIALTY CASCADE CONSTRAINTS PURGE;

--
-- BAS_ELEMENT_TYPE_SPECIALTY  (Table) 
--
CREATE TABLE ROCA.BAS_ELEMENT_TYPE_SPECIALTY
(
  BAS_ELEMENT_TYPE_ID  NUMBER(9)                NOT NULL,
  SPECIALTY_ID         NUMBER(9)                NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.BAS_FIELD_DEFINITIONS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.BAS_FIELD_DEFINITIONS CASCADE CONSTRAINTS PURGE;

--
-- BAS_FIELD_DEFINITIONS  (Table) 
--
CREATE TABLE ROCA.BAS_FIELD_DEFINITIONS
(
  BAS_FIELD_DEFINITION_ID  NUMBER(9)            NOT NULL,
  TYPE                     NUMBER(3)            NOT NULL,
  FIELD_ORDER              NUMBER(2)            NOT NULL,
  CODE                     VARCHAR2(50 CHAR)    NOT NULL,
  NAME                     VARCHAR2(200 CHAR)   NOT NULL,
  LENGTH                   NUMBER(2)            NOT NULL,
  BAS_ELEMENT_TYPE_ID      NUMBER(9)            NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


ALTER TABLE ROCA.BAS_CODE_FIELDS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROCA.BAS_CODE_FIELDS CASCADE CONSTRAINTS PURGE;

--
-- BAS_CODE_FIELDS  (Table) 
--
CREATE TABLE ROCA.BAS_CODE_FIELDS
(
  BAS_CODE_FIELD_ID        NUMBER(9)            NOT NULL,
  BAS_ELEMENT_ID           NUMBER(9)            NOT NULL,
  BAS_CODE_ID              NUMBER(9)            NOT NULL,
  BAS_FIELD_DEFINITION_ID  NUMBER(9)            NOT NULL
)
TABLESPACE TS_ROCA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


--
-- BAS_ELEMENT_TYPE_SPECIALTY_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.BAS_ELEMENT_TYPE_SPECIALTY_PK ON ROCA.BAS_ELEMENT_TYPE_SPECIALTY
(BAS_ELEMENT_TYPE_ID, SPECIALTY_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- BAS_FIELD_DEFINITIONS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.BAS_FIELD_DEFINITIONS_PK ON ROCA.BAS_FIELD_DEFINITIONS
(BAS_FIELD_DEFINITION_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- BAS_CODE_FIELDS_PK  (Index) 
--
CREATE UNIQUE INDEX ROCA.BAS_CODE_FIELDS_PK ON ROCA.BAS_CODE_FIELDS
(BAS_CODE_FIELD_ID)
TABLESPACE TS_ROCA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


--
-- BAS_FIELD_DEFINITIONS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.BAS_FIELD_DEFINITIONS_TRG
BEFORE INSERT
ON ROCA.BAS_FIELD_DEFINITIONS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column BAS_FIELD_DEFINITION_ID
  :new.BAS_FIELD_DEFINITION_ID := BAS_FIELD_DEFINITIONS_SEQ.nextval;
END BAS_FIELD_DEFINITIONS_TRG;
/


--
-- BAS_CODE_FIELDS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER ROCA.BAS_CODE_FIELDS_TRG
BEFORE INSERT
ON ROCA.BAS_CODE_FIELDS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column BAS_CODE_FIELD_ID
  :new.BAS_CODE_FIELD_ID := BAS_CODE_FIELDS_SEQ.nextval;
END BAS_CODE_FIELDS_TRG;
/


-- 
-- Non Foreign Key Constraints for Table DOCUMENTS_RAW 
-- 
ALTER TABLE ROCA.DOCUMENTS_RAW ADD (
  CONSTRAINT DOCUMENTS_RAW_U01
  UNIQUE (DOCNUMBER)
  USING INDEX ROCA.DOCUMENTS_RAW_U01
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table MATERIALS 
-- 
ALTER TABLE ROCA.MATERIALS ADD (
  CONSTRAINT MATERIALS_PK
  PRIMARY KEY
  (MATERIAL_ID)
  USING INDEX ROCA.MATERIALS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table UNITS 
-- 
ALTER TABLE ROCA.UNITS ADD (
  CONSTRAINT UNITS_PK
  PRIMARY KEY
  (UNIT_ID)
  USING INDEX ROCA.UNITS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table SPECIALTIES 
-- 
ALTER TABLE ROCA.SPECIALTIES ADD (
  CONSTRAINT SPECIALTIES_PK
  PRIMARY KEY
  (SPECIALTY_ID)
  USING INDEX ROCA.SPECIALTIES_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table EIMATERIALS 
-- 
ALTER TABLE ROCA.EIMATERIALS ADD (
  CONSTRAINT EIMATERIALS_PK
  PRIMARY KEY
  (MATERIAL_ID)
  USING INDEX ROCA.EIMATERIALS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table PMATERIALS 
-- 
ALTER TABLE ROCA.PMATERIALS ADD (
  CONSTRAINT PMATERIALS_PK
  PRIMARY KEY
  (MATERIAL_ID)
  USING INDEX ROCA.PMATERIALS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table USERS 
-- 
ALTER TABLE ROCA.USERS ADD (
  CONSTRAINT USERS_PK
  PRIMARY KEY
  (ID)
  USING INDEX ROCA.USERS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table PROJECTS 
-- 
ALTER TABLE ROCA.PROJECTS ADD (
  CONSTRAINT PROJECTS_PK
  PRIMARY KEY
  (PROJECT_ID)
  USING INDEX ROCA.PROJECTS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table USER_SPECIALTY 
-- 
ALTER TABLE ROCA.USER_SPECIALTY ADD (
  CONSTRAINT USER_SPECIALTY_PK
  PRIMARY KEY
  (USER_ID, SPECIALTY_ID)
  USING INDEX ROCA.USER_SPECIALTY_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table MATERIAL_LISTS 
-- 
ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_PK
  PRIMARY KEY
  (ML_ID)
  USING INDEX ROCA.MATERIAL_LISTS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table ML_ITEMS 
-- 
ALTER TABLE ROCA.ML_ITEMS ADD (
  CONSTRAINT ML_ITEMS_PK
  PRIMARY KEY
  (ML_ITEM_ID)
  USING INDEX ROCA.ML_ITEMS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table LOOKUPS 
-- 
ALTER TABLE ROCA.LOOKUPS ADD (
  CONSTRAINT LOOKUPS_PK
  PRIMARY KEY
  (LOOKUP_ID)
  USING INDEX ROCA.LOOKUPS_PK
  ENABLE VALIDATE);

ALTER TABLE ROCA.LOOKUPS ADD (
  CONSTRAINT LOOKUPS_U01
  UNIQUE (TYPE, CODE)
  USING INDEX ROCA.LOOKUPS_U01
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table EIMATERIAL_DETAILS 
-- 
ALTER TABLE ROCA.EIMATERIAL_DETAILS ADD (
  CONSTRAINT EIMATERIAL_DETAILS_PK
  PRIMARY KEY
  (MATERIAL_ID)
  USING INDEX ROCA.EIMATERIAL_DETAILS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table TAGGABLE_TYPES 
-- 
ALTER TABLE ROCA.TAGGABLE_TYPES ADD (
  CONSTRAINT TAGGABLE_TYPES_PK
  PRIMARY KEY
  (TAGGABLE_TYPE_ID)
  USING INDEX ROCA.TAGGABLE_TYPES_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table TAGGABLE_ATTRIBUTES 
-- 
ALTER TABLE ROCA.TAGGABLE_ATTRIBUTES ADD (
  CONSTRAINT TAGGABLE_ATTRIBUTES_PK
  PRIMARY KEY
  (TAGGABLE_ATTRIBUTE_ID)
  USING INDEX ROCA.TAGGABLE_ATTRIBUTES_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table DOCUMENTS 
-- 
ALTER TABLE ROCA.DOCUMENTS ADD (
  CONSTRAINT DOCUMENTS_PK
  PRIMARY KEY
  (ID)
  USING INDEX ROCA.DOCUMENTS_PK
  ENABLE VALIDATE);

ALTER TABLE ROCA.DOCUMENTS ADD (
  CONSTRAINT DOCUMENTS_U01
  UNIQUE (PROJECT_ID, DOCNUMBER)
  USING INDEX ROCA.DOCUMENTS_U01
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table TIMESHEETS 
-- 
ALTER TABLE ROCA.TIMESHEETS ADD (
  CONSTRAINT TIMESHEETS_PK
  PRIMARY KEY
  (ID)
  USING INDEX ROCA.TIMESHEETS_PK
  ENABLE VALIDATE);

ALTER TABLE ROCA.TIMESHEETS ADD (
  CONSTRAINT TIMESHEETS_U01
  UNIQUE (USER_ID, SPECIALTY_ID, CONTROL_DATE)
  USING INDEX ROCA.TIMESHEETS_U01
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table TIMESHEET_ITEMS 
-- 
ALTER TABLE ROCA.TIMESHEET_ITEMS ADD (
  CONSTRAINT TIMESHEET_ITEMS_PK
  PRIMARY KEY
  (ID)
  USING INDEX ROCA.TIMESHEET_ITEMS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table BAS_CODES 
-- 
ALTER TABLE ROCA.BAS_CODES ADD (
  CONSTRAINT BAS_CODES_PK1
  PRIMARY KEY
  (BAS_CODE_ID)
  USING INDEX ROCA.BAS_CODES_PK1
  ENABLE VALIDATE);

ALTER TABLE ROCA.BAS_CODES ADD (
  CONSTRAINT BAS_CODES_U01
  UNIQUE (FIELD, CODE)
  USING INDEX ROCA.BAS_CODES_U01
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table MAT_PIPING_AP 
-- 
ALTER TABLE ROCA.MAT_PIPING_AP ADD (
  CONSTRAINT MAT_PIPING_AP_PK
  PRIMARY KEY
  (ID)
  USING INDEX ROCA.MAT_PIPING_AP_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table MAT_PIPING 
-- 
ALTER TABLE ROCA.MAT_PIPING ADD (
  CONSTRAINT MAT_PIPING_PK
  PRIMARY KEY
  (ID)
  USING INDEX ROCA.MAT_PIPING_PK
  ENABLE VALIDATE);

ALTER TABLE ROCA.MAT_PIPING ADD (
  CONSTRAINT MAT_PIPING_U01
  UNIQUE (OEP_CODE)
  USING INDEX ROCA.MAT_PIPING_U01
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table BAS_ELEMENTS 
-- 
ALTER TABLE ROCA.BAS_ELEMENTS ADD (
  CONSTRAINT BAS_ELEMENTS_PK
  PRIMARY KEY
  (BAS_ELEMENT_ID)
  USING INDEX ROCA.BAS_ELEMENTS_PK
  ENABLE VALIDATE);

ALTER TABLE ROCA.BAS_ELEMENTS ADD (
  UNIQUE (FULL_CODE)
  USING INDEX
    TABLESPACE TS_ROCA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table BAS_CODES_RAW 
-- 
ALTER TABLE ROCA.BAS_CODES_RAW ADD (
  CONSTRAINT BAS_CODES_RAW_U01
  UNIQUE (FIELD, CODE)
  USING INDEX ROCA.BAS_CODES_RAW_U01
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table BAS_CLASSES 
-- 
ALTER TABLE ROCA.BAS_CLASSES ADD (
  CONSTRAINT BAS_CLASSES_PK
  PRIMARY KEY
  (BAS_CLASS_ID)
  USING INDEX ROCA.BAS_CLASSES_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table BAS_CLASS_ATTRIBUTES 
-- 
ALTER TABLE ROCA.BAS_CLASS_ATTRIBUTES ADD (
  CONSTRAINT BAS_CLASS_ATTRIBUTES_PK
  PRIMARY KEY
  (BAS_CLASS_ATTRIBUTE_ID)
  USING INDEX ROCA.BAS_CLASS_ATTRIBUTES_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table BAS_ELEMENT_TYPES 
-- 
ALTER TABLE ROCA.BAS_ELEMENT_TYPES ADD (
  CONSTRAINT BAS_ELEMENT_TYPES_PK
  PRIMARY KEY
  (BAS_ELEMENT_TYPE_ID)
  USING INDEX ROCA.BAS_ELEMENT_TYPES_PK
  ENABLE VALIDATE);

ALTER TABLE ROCA.BAS_ELEMENT_TYPES ADD (
  CONSTRAINT BAS_ELEMENT_TYPES_U01
  UNIQUE (CODE)
  USING INDEX ROCA.BAS_ELEMENT_TYPES_U01
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table BAS_ELEMENT_TYPE_SPECIALTY 
-- 
ALTER TABLE ROCA.BAS_ELEMENT_TYPE_SPECIALTY ADD (
  CONSTRAINT BAS_ELEMENT_TYPE_SPECIALTY_PK
  PRIMARY KEY
  (BAS_ELEMENT_TYPE_ID, SPECIALTY_ID)
  USING INDEX ROCA.BAS_ELEMENT_TYPE_SPECIALTY_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table BAS_FIELD_DEFINITIONS 
-- 
ALTER TABLE ROCA.BAS_FIELD_DEFINITIONS ADD (
  CONSTRAINT BAS_FIELD_DEFINITIONS_PK
  PRIMARY KEY
  (BAS_FIELD_DEFINITION_ID)
  USING INDEX ROCA.BAS_FIELD_DEFINITIONS_PK
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table BAS_CODE_FIELDS 
-- 
ALTER TABLE ROCA.BAS_CODE_FIELDS ADD (
  CONSTRAINT BAS_CODE_FIELDS_PK
  PRIMARY KEY
  (BAS_CODE_FIELD_ID)
  USING INDEX ROCA.BAS_CODE_FIELDS_PK
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table EIMATERIALS 
-- 
ALTER TABLE ROCA.EIMATERIALS ADD (
  CONSTRAINT EIMATERIALS_FK1 
  FOREIGN KEY (MATERIAL_ID) 
  REFERENCES ROCA.MATERIALS (MATERIAL_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table PMATERIALS 
-- 
ALTER TABLE ROCA.PMATERIALS ADD (
  CONSTRAINT PMATERIALS_FK1 
  FOREIGN KEY (MATERIAL_ID) 
  REFERENCES ROCA.MATERIALS (MATERIAL_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table PROJECTS 
-- 
ALTER TABLE ROCA.PROJECTS ADD (
  CONSTRAINT PROJECTS_FK1 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES ROCA.PROJECTS (PROJECT_ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table USER_SPECIALTY 
-- 
ALTER TABLE ROCA.USER_SPECIALTY ADD (
  CONSTRAINT USER_SPECIALTY_FK2 
  FOREIGN KEY (SPECIALTY_ID) 
  REFERENCES ROCA.SPECIALTIES (SPECIALTY_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.USER_SPECIALTY ADD (
  CONSTRAINT USER_SPECIALTY_FK1 
  FOREIGN KEY (USER_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table MATERIAL_LISTS 
-- 
ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK3 
  FOREIGN KEY (SPECIALTY_ID) 
  REFERENCES ROCA.SPECIALTIES (SPECIALTY_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK4 
  FOREIGN KEY (CREATOR_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK5 
  FOREIGN KEY (UPDATER_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK6 
  FOREIGN KEY (REVISOR_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK7 
  FOREIGN KEY (APPROVER_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK8 
  FOREIGN KEY (PROJECT_ID) 
  REFERENCES ROCA.PROJECTS (PROJECT_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.MATERIAL_LISTS ADD (
  CONSTRAINT MATERIAL_LISTS_FK2 
  FOREIGN KEY (PREV_REV_ML_ID) 
  REFERENCES ROCA.MATERIAL_LISTS (ML_ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table ML_ITEMS 
-- 
ALTER TABLE ROCA.ML_ITEMS ADD (
  CONSTRAINT ML_ITEMS_FK2 
  FOREIGN KEY (MATERIAL_ID) 
  REFERENCES ROCA.MATERIALS (MATERIAL_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.ML_ITEMS ADD (
  CONSTRAINT ML_ITEMS_FK1 
  FOREIGN KEY (ML_ID) 
  REFERENCES ROCA.MATERIAL_LISTS (ML_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table EIMATERIAL_DETAILS 
-- 
ALTER TABLE ROCA.EIMATERIAL_DETAILS ADD (
  CONSTRAINT EIMATERIAL_DETAILSFK1 
  FOREIGN KEY (MATERIAL_ID) 
  REFERENCES ROCA.EIMATERIALS (MATERIAL_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table TAGGABLE_TYPES 
-- 
ALTER TABLE ROCA.TAGGABLE_TYPES ADD (
  CONSTRAINT TAGGABLE_TYPES_FK1 
  FOREIGN KEY (SPECIALTY_ID) 
  REFERENCES ROCA.SPECIALTIES (SPECIALTY_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.TAGGABLE_TYPES ADD (
  CONSTRAINT TAGGABLE_TYPES_FK2 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES ROCA.TAGGABLE_TYPES (TAGGABLE_TYPE_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table TAGGABLE_ATTRIBUTES 
-- 
ALTER TABLE ROCA.TAGGABLE_ATTRIBUTES ADD (
  CONSTRAINT TAGGABLE_ATTRIBUTES_FK1 
  FOREIGN KEY (TAGGABLE_TYPE_ID) 
  REFERENCES ROCA.TAGGABLE_TYPES (TAGGABLE_TYPE_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table DOCUMENTS 
-- 
ALTER TABLE ROCA.DOCUMENTS ADD (
  CONSTRAINT DOCUMENTS_FK2 
  FOREIGN KEY (SPECIALTY_ID) 
  REFERENCES ROCA.SPECIALTIES (SPECIALTY_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.DOCUMENTS ADD (
  CONSTRAINT DOCUMENTS_FK1 
  FOREIGN KEY (PROJECT_ID) 
  REFERENCES ROCA.PROJECTS (PROJECT_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.DOCUMENTS ADD (
  CONSTRAINT DOCUMENTS_FK3 
  FOREIGN KEY (TYPE_ID) 
  REFERENCES ROCA.LOOKUPS (LOOKUP_ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table TIMESHEETS 
-- 
ALTER TABLE ROCA.TIMESHEETS ADD (
  CONSTRAINT TIMESHEETS_FK3 
  FOREIGN KEY (SPECIALTY_ID) 
  REFERENCES ROCA.SPECIALTIES (SPECIALTY_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.TIMESHEETS ADD (
  CONSTRAINT TIMESHEETS_FK1 
  FOREIGN KEY (USER_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.TIMESHEETS ADD (
  CONSTRAINT TIMESHEETS_FK2 
  FOREIGN KEY (LEADER_ID) 
  REFERENCES ROCA.USERS (ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table TIMESHEET_ITEMS 
-- 
ALTER TABLE ROCA.TIMESHEET_ITEMS ADD (
  CONSTRAINT TIMESHEET_ITEMS_FK4 
  FOREIGN KEY (SUBPROJECT_ID) 
  REFERENCES ROCA.PROJECTS (PROJECT_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.TIMESHEET_ITEMS ADD (
  CONSTRAINT TIMESHEET_ITEMS_FK3 
  FOREIGN KEY (TASK_ID) 
  REFERENCES ROCA.LOOKUPS (LOOKUP_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.TIMESHEET_ITEMS ADD (
  CONSTRAINT TIMESHEET_ITEMS_FK2 
  FOREIGN KEY (DOCUMENT_ID) 
  REFERENCES ROCA.DOCUMENTS (ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.TIMESHEET_ITEMS ADD (
  CONSTRAINT TIMESHEET_ITEMS_FK1 
  FOREIGN KEY (TIMESHEET_ID) 
  REFERENCES ROCA.TIMESHEETS (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table BAS_CLASS_ATTRIBUTES 
-- 
ALTER TABLE ROCA.BAS_CLASS_ATTRIBUTES ADD (
  CONSTRAINT BAS_CLASS_ATTRIBUTES_FK1 
  FOREIGN KEY (BAS_CLASS_ID) 
  REFERENCES ROCA.BAS_CLASSES (BAS_CLASS_ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table BAS_ELEMENT_TYPES 
-- 
ALTER TABLE ROCA.BAS_ELEMENT_TYPES ADD (
  CONSTRAINT BAS_ELEMENT_TYPES_FK1 
  FOREIGN KEY (BAS_CLASS_ID) 
  REFERENCES ROCA.BAS_CLASSES (BAS_CLASS_ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table BAS_ELEMENT_TYPE_SPECIALTY 
-- 
ALTER TABLE ROCA.BAS_ELEMENT_TYPE_SPECIALTY ADD (
  CONSTRAINT BAS_ELEMENT_TYPE_SPECIALTY_FK2 
  FOREIGN KEY (SPECIALTY_ID) 
  REFERENCES ROCA.SPECIALTIES (SPECIALTY_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.BAS_ELEMENT_TYPE_SPECIALTY ADD (
  CONSTRAINT BAS_ELEMENT_TYPE_SPECIALTY_FK1 
  FOREIGN KEY (BAS_ELEMENT_TYPE_ID) 
  REFERENCES ROCA.BAS_ELEMENT_TYPES (BAS_ELEMENT_TYPE_ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table BAS_FIELD_DEFINITIONS 
-- 
ALTER TABLE ROCA.BAS_FIELD_DEFINITIONS ADD (
  CONSTRAINT BAS_FIELD_DEFINITIONS_FK1 
  FOREIGN KEY (BAS_ELEMENT_TYPE_ID) 
  REFERENCES ROCA.BAS_ELEMENT_TYPES (BAS_ELEMENT_TYPE_ID)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table BAS_CODE_FIELDS 
-- 
ALTER TABLE ROCA.BAS_CODE_FIELDS ADD (
  CONSTRAINT BAS_CODE_FIELDSFK2 
  FOREIGN KEY (BAS_CODE_ID) 
  REFERENCES ROCA.BAS_CODES (BAS_CODE_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.BAS_CODE_FIELDS ADD (
  CONSTRAINT BAS_CODE_FIELDS_FK1 
  FOREIGN KEY (BAS_FIELD_DEFINITION_ID) 
  REFERENCES ROCA.BAS_FIELD_DEFINITIONS (BAS_FIELD_DEFINITION_ID)
  ENABLE VALIDATE);

ALTER TABLE ROCA.BAS_CODE_FIELDS ADD (
  CONSTRAINT BAS_CODE_FIELDS_FK3 
  FOREIGN KEY (BAS_ELEMENT_ID) 
  REFERENCES ROCA.BAS_ELEMENTS (BAS_ELEMENT_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);